# .github/workflows/ci-and-deploy.yml
name: CI/CD to Main on successful pass

on:
  push:
    branches:
      - dev # Trigger on pushes to your development branch
      - feature/** # Or any feature branch pattern

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment (e.g., Python, Node.js)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements*.txt

      - name: Run tests
        run: |
          pytest
          ruff check src/


  deploy_to_main:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.name "Furangel_Deployment_bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get source commit details
        id: get_source_commit_info # Assign an ID to this step to get its outputs
        run: |
          # Get the commit message of the triggering commit
          SOURCE_COMMIT_MESSAGE_RAW="${{ github.event.head_commit.message }}"
          # Use 'sed' to escape newlines if the message is multi-line, so it can be passed as a single line output
          SOURCE_COMMIT_MESSAGE_ESCAPED=$(echo "$SOURCE_COMMIT_MESSAGE_RAW" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "source_commit_message=$SOURCE_COMMIT_MESSAGE_ESCAPED" >> "$GITHUB_OUTPUT"
          
          # Get the first 7 characters for a short SHA using substring()
          # Direct echo of the GitHub Actions expression into GITHUB_OUTPUT
          echo "source_commit_sha_short=${{ github.sha.substring(0, 7) }}" >> "$GITHUB_OUTPUT"

          # Get author name
          echo "source_commit_author=${{ github.event.head_commit.author.name }}" >> "$GITHUB_OUTPUT"
          # echo "source_commit_timestamp=${{ github.event.head_commit.timestamp }}" >> "$GITHUB_OUTPUT"

      - name: Push changes to main
        run: |
          git push origin main

